# Generated by Django 6.0.3 on 2026-03-11 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('esmaltado', 'Esmaltado/Efecto'), ('charm', 'Charm/Dije'), ('cristal', 'Cristal/Pedrería'), ('extra', 'Servicio Extra')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloUña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='catalogo/')),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('foto_diseno', models.ImageField(upload_to='citas/disenos/')),
                ('foto_perfil_una', models.ImageField(upload_to='citas/perfiles/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('notas_cliente', models.TextField(blank=True)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='nails.cita')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nails.insumo')),
            ],
        ),
    ]
