# Generated by Django 6.0.3 on 2026-03-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='sistema_unas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
