# Generated by Django 6.0.3 on 2026-03-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0002_cita_sistema_unas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Evaluación'), ('cotizada', 'Esperando Confirmación de Clienta'), ('confirmada', 'Confirmada y Agendada')], default='pendiente', max_length=20),
        ),
    ]
