# Generated by Django 6.0.3 on 2026-03-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0003_cita_precio_base_alter_cita_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Evaluación'), ('cotizada', 'Esperando Confirmación de Clienta'), ('precio_aceptado', 'Clienta Aceptó (Por Confirmar)'), ('confirmada', 'Confirmada y Agendada')], default='pendiente', max_length=20),
        ),
    ]
