# Generated by Django 6.0.3 on 2026-03-14 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0005_perfilcliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='costo_estimado',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='fecha_solicitud',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='modelouña',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='modelouña',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='modelouña',
            name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='cita',
            name='notas_cliente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detallecita',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nails.insumo'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
