# Generated by Django 6.0.3 on 2026-03-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0006_remove_cita_costo_estimado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilcliente',
            name='usuario',
        ),
        migrations.AddField(
            model_name='perfilcliente',
            name='usuario_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='notas_internas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
