# Generated by Django 6.0.3 on 2026-03-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0007_remove_perfilcliente_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
