# Generated by Django 6.0.3 on 2026-03-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0008_cita_costo_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelouña',
            name='descripcion',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
