# Generated by Django 6.0.3 on 2026-03-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0009_modelouña_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='desglose_cotizacion',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
