# Generated by Django 6.0.3 on 2026-03-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0010_cita_desglose_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='recomendacion_admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='costo_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
