# Generated by Django 6.0.3 on 2026-03-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0011_cita_edad_cita_recomendacion_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='hora_modificada',
            field=models.BooleanField(default=False),
        ),
    ]
