# Generated by Django 6.0.3 on 2026-03-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0012_cita_hora_modificada'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='codigo_pago',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
