# Generated by Django 6.0.3 on 2026-03-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0013_cita_codigo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='duracion_estimada',
            field=models.IntegerField(blank=True, default=120, null=True),
        ),
    ]
