# Generated by Django 6.0.3 on 2026-03-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0014_cita_duracion_estimada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Evaluación'), ('cotizada', 'Esperando Confirmación de Clienta'), ('precio_aceptado', 'Clienta Aceptó (Por Confirmar)'), ('confirmada', 'Confirmada y Agendada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
    ]
