# Generated by Django 6.0.3 on 2026-03-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0015_alter_cita_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='estado_anterior',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
