# Generated by Django 6.0.3 on 2026-03-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0016_cita_estado_anterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='cancelado_por',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
